GoogleChromeLabs/bubblewrap

README.md
lib/GradleWrapper.js
lib/androidSdk/AndroidSdkTools.js
lib/jdk/JdkHelper.js

- Adjusts PATH and executable references to enable the CLI to run on Windows.
- Removes warning on Windows compatibility from the README

Makes `llama-pack` compatible with Windows

---

src/lib/TwaGenerator.js

- TwaGenerator.js is using the wrong import, which causes
initialising or updating a TWA to fail

Fix import for jimp-resize

---

.eslintrc.json
package-lock.json
package.json
src/index.ts
src/spec/lib/ConfigSpec.ts

I think ESLint only checks JS files by default. Adjusts the command to check ts files and adds the typescript parser. [@typescript-eslint/eslint-plugin](https://github.com/typescript-eslint/typescript-eslint) could be added for TS-specific rules.

Configure eslint to lint ts files

---

src/lib/androidSdk/AndroidSdkTools.js
src/lib/util.js
src/spec/lib/androidSdk/AndroidSdkToolsSpec.js

Paths with space fix

---

src/cli/cmds/update.js
src/lib/TwaGenerator.js

Fixes `UnhandledPromiseRejection` errors

---

template_project/gradle/wrapper/gradle-wrapper.properties

When you create a new Android Project from Android Studio, it on the bottom.
Just to less diffing if you come from an Android Studio project.

Move distributionUrl to the bottom

---

src/lib/TwaManifest.ts
src/spec/lib/TwaManifestSpec.ts

Related to https://github.com/GoogleChromeLabs/llama-pack/issues/66#issuecomment-574656372
Then, at any time the user can change the value from `twa-manifest.json` and `build.gradle`.

Update default navigationColor to black as PWAs

---

src/lib/GradleWrapper.js

@JudahGabriel drafted this to enable customizing the Gradle Wrapper.

Allows Customizing Project Location on Gradle Wrapper

---

src/lib/jdk/KeyTool.ts

Fixes the issue where e.g. the key password contains a hyphen.

Escaping user input to key tool

---

template_project/app/build.gradle
template_project/app/src/main/AndroidManifest.xml

- Uses android-browser-helper-1.1.0
- Adds FocusActivity to AndroidManifest.xml
Closes #80

Updates to use android-browser-helper 1.1.0

---

.eslintrc.json
src/cli/cmds/help.ts
src/cli/index.ts

Adds help messages to the help command

---

src/cli/cmds/build.ts

- Developers can use the `LLAMA_PACK_KEYSTORE_PASSWORD` and
`LLAMA_PACK_KEY_PASSWORD` enviroment variables to set the
keystore and key passwords.
- When both passwords are set, they will be used instead of
prompting the users for the passwords.
Closes #30

Allows automated builds

---

src/index.ts
src/lib/TwaGenerator.ts

- When status is not 200, the generation fails with an unclear
error message.
- Added an explicit check for the status, with a message that is
easier to read.

Report an Error when `iconUrl` is not 200

---

src/cli/cmds/help.ts
src/cli/cmds/update.ts
src/lib/TwaManifest.ts
src/spec/lib/TwaManifestSpec.ts
template_project/app/build.gradle

- Renamed `appVersion` to `appVersionName` on `TwaManifest`.
- Added `appVersionCode` to `TwaManifest.
- Updated the template project to use `appVersionName` and
`appVersionCode` from the TWA Manifest.
- Added new option `skipVersinUpgrade` to `update`, to regenerate
project without updating versions.
- Added new option `appVersionName` to set a specific version name
when updating the project
- `update` generates new versions by increasing `appVersionCode`
by 1. When generating a new `appVersionName`, the value of
`--appVersionName` is used if set. Otherwise, an attempt to
generate it from the `appVersionCode` is made. If not possible,
the user is prompted to input a version name.
Closes #74 
Closes #3

`update` upgrades `versionCode` and `versionName`

---

src/lib/TwaGenerator.ts
src/lib/TwaManifest.ts
src/spec/lib/TwaManifestSpec.ts
template_project/app/build.gradle
template_project/app/src/main/AndroidManifest.xml

- When webManifestUrl is set on twa-manifest.json, it includes a
`web-manifest-url` meta-tag on AndroidManifest.xml with the
correct value and creates a web-app-manifest.json at /res/raw
- When webManifestUrl ist not set, it doesn't add any meta tag
Closes #88

Adds web-manifest-url meta-tag and web-app-manifest.json

---

src/cli/cmds/init.ts
src/lib/TwaGenerator.ts
src/lib/TwaManifest.ts
src/spec/lib/TwaManifestSpec.ts
template_project/app/build.gradle

- Change `TwaManifest.shortcuts` to be `ShortcutInfo[]` instead
of `string`.
- Refactor code to reflect that change
- Fixes reversed if condition in `init` leading to not adding
shortcuts.
- Test the result of `generateShortcut()`
- Uses correct `LauncherActivity` in `build.gradle`
- Truncates `short_name` to 12 characters, when unavailable and copying from `name`. Recommendation for 12 chars [here](https://developer.chrome.com/apps/manifest/name#short_name)

Refactors TwaManifest.shortcuts

---

packages/cli/src/lib/cmds/init.ts
packages/core/src/lib/TwaGenerator.ts

- [cli] Fixes validation for maskable images
- [core] Checks for content-type when downloading images and
throws an error when the content-type is invalid.

Fixes handling of maskable images

---

packages/cli/src/lib/Cli.ts
packages/cli/src/lib/config.ts
packages/core/src/lib/Config.ts

Moves functions for reading/writing Config into the cli, since none of them are used in core. check() has been removed since its no longer used.
Also added a `path` parameter so a prompt could be added to allow custom config paths.
Core Config is now just a data class, so perhaps it should be changed to an interface.

Move Config read/write into cli

---

packages/core/template_project/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
packages/core/template_project/gradle.properties

- Background for transparent icons is white.
- ~~Moves icon to the foreground layer, instead of background.~~
- Adds `android.useAndroidX=true` to `build.gradle` to make importing the project into Android Studio more seamless (unrelated to the icon).
Closes #112

Adaptative Icons Improvements

---

packages/core/template_project/app/build.gradle

- Recent versions of Chrome only run on Android 4.4, KitKat
(API level 19) and above.
- Even with the planned WebView fallback, up to android 5.0,
Lollipop (API Level 22), the WebView wasn't updatable via
the Play Store and is unlikely to render modern Web Apps
correctly.
- The Android dashboard (https://developer.android.com/about/dashboards)
points to API level 16 to 19 accounting for 3.2% of users.

Increases minSdkVersion to 19

---

packages/core/src/lib/TwaManifest.ts
packages/core/src/spec/lib/TwaManifestSpec.ts
packages/core/template_project/app/build.gradle
packages/core/template_project/app/src/main/AndroidManifest.xml

- Updates to using android-browser-helper-1.2.0
- Adds an option to enable the WebView fallback on the twa-manifest.json

Updates android-browser-helper and enables WebView fallback on config

---

README.md
packages/cli/package-lock.json
packages/cli/package.json
packages/cli/src/index.ts
packages/cli/src/lib/Cli.ts
packages/cli/src/lib/cmds/build.ts
packages/cli/src/lib/cmds/help.ts
packages/cli/src/lib/cmds/init.ts
packages/cli/src/lib/cmds/update.ts
packages/cli/src/lib/cmds/validate.ts
packages/cli/src/lib/pwaValidationHelper.ts
packages/validator/README.md
packages/validator/jasmine.json
packages/validator/package-lock.json
packages/validator/package.json
packages/validator/src/index.ts
packages/validator/src/lib/PwaValidator.ts
packages/validator/src/lib/psi/PageSpeedInsights.ts
packages/validator/src/lib/psi/PsiResult.ts
packages/validator/src/lib/psi/index.ts
packages/validator/src/spec/PwaValidatorSpec.ts
packages/validator/src/spec/psi/PageSpeedInsightsSpec.ts
packages/validator/tsconfig.json

- Adds a validator module that validates PWAs for the Trusted Web
Activity quality criteria.
- The module uses the PageSpeed Insights API to run and collect
Lighthouse scoring information.
- Adds a `validate` command to `@bubblewrap/cli`.
- Starts work on #104

Adds a validator module to Bubblewrap

---

packages/cli/package-lock.json
packages/cli/package.json
packages/cli/src/lib/cmds/build.ts
packages/cli/src/lib/cmds/init.ts
packages/cli/src/lib/cmds/update.ts
packages/cli/src/lib/inputHelpers.ts
packages/cli/src/spec/inputHelpersSpec.ts
packages/core/src/index.ts
packages/core/src/lib/util.ts
packages/core/src/spec/lib/utilSpec.ts

- Implements validation and tests
- Improves some error messages on the CLI

Implements input validation for the AplicationId

---

packages/cli/src/lib/cmds/build.ts
packages/cli/src/lib/cmds/init.ts
packages/cli/src/lib/inputHelpers.ts
packages/core/src/lib/TwaGenerator.ts
packages/core/src/lib/TwaManifest.ts
packages/core/src/lib/util.ts
packages/core/src/spec/lib/TwaManifestSpec.ts
packages/core/src/spec/lib/utilSpec.ts

- generatePackageId returns an error string  when a correct
package cannot be generated from the input.
- validatePackageId returns an error string if the input is
invalid or null if there's no error.
- validateNotEmpty introduced in `core`. `notEmpty()` in
`cli/inputHelpers()` uses it.
- TwaGenerator#validate() changed to return an error string if the
packageId is invalid or null if if it is valid. It also validates
the packageId

Improves packageId generation / validation

---

packages/core/src/lib/androidSdk/AndroidSdkTools.ts
packages/core/src/spec/lib/androidSdk/AndroidSdkToolsSpec.ts

Setting ANDROID_HOME via should be enough for sdkmanager to work,
but version 6200805 of the the Android Command Line tools only work
if sdk_root is not set.

Fix for CLI to work on latest Android CLI Tools

---

package-lock.json
packages/core/src/lib/androidSdk/AndroidSdkTools.ts
packages/core/src/spec/lib/androidSdk/AndroidSdkToolsSpec.ts

- on Windows, escaping --sdk_root with `"` causes the sdkmanager
to error. Removing the escape char on Windows.
- We'll need to throw an error when a path with spaces is passed
in the config, but working on that on another PR.

Fixes --sdk_root parameter on Windows

---

packages/cli/src/lib/cmds/build.ts
packages/core/src/lib/androidSdk/AndroidSdkTools.ts
packages/core/src/spec/lib/androidSdk/AndroidSdkToolsSpec.ts

- throws error on constructor when then path to androidSdkTools doesn't exist
- throws error when installing build tools and path to sdkmanager doesn't exist

Improves AndroidSdkTools errors

---

packages/cli/package-lock.json
packages/cli/package.json
packages/cli/src/lib/Cli.ts

Uses `semver` to check the Node.js version and throws an error if an unsupported version is used.
Closes #152

CLI checks minimum supported Node.js version

---

packages/cli/README.md
packages/cli/src/lib/Cli.ts
packages/cli/src/lib/cmds/help.ts
packages/cli/src/lib/cmds/install.ts
packages/core/src/lib/androidSdk/AndroidSdkTools.ts
packages/core/src/lib/util.ts
packages/core/src/spec/lib/androidSdk/AndroidSdkToolsSpec.ts

`bubblewrap install` allows developers to install an APK to a
connected development device to test the application without
the need to find the correct adb commands.
Closes #49

Adds a `bubblewrap install` command

---

packages/core/template_project/app/build.gradle

- Updates to use android-browser-helper 1.3.0, so apps generated
with Bubblewrap get the bug fixes.

Updates android-browser-helper version

---

packages/cli/src/lib/cmds/build.ts
packages/cli/src/lib/cmds/install.ts
packages/core/src/lib/Log.ts
packages/core/src/lib/androidSdk/AndroidSdkTools.ts
packages/core/src/spec/lib/androidSdk/AndroidSdkToolsSpec.ts
packages/validator/src/lib/PwaValidator.ts

- When the PSI request fails, show an error message but don't fail
the entire build.
- Appends `-r` to the APK install command to remove an existing app
with the same packageId and reinstall it.

Prevent build failing when PSI fails

---

packages/cli/src/lib/cmds/build.ts
packages/core/src/lib/DigitalAssetLinks.ts
packages/core/src/spec/lib/DigitalAssetLinksSpec.ts

- Uses information from they keystore and the applicationId to
generate the Digital Asset Links file that matches the key used
to build the signed APK.
- If the developer opted into Play Signing by Play the fingerprint
won't match and the Digital Asset Links validation will not
validate
Closes #5

Generates assetlinks.json when building the App

---

README.md

When I clicked on the badge - it opened badge file (image).
I think it would be more useful if it will open [workflow page](https://github.com/GoogleChromeLabs/bubblewrap/actions?query=workflow%3A%22Node+CI%22)

Link badge to workflow page

---

packages/core/src/lib/androidSdk/AndroidSdkTools.ts
packages/core/src/lib/jdk/JdkHelper.ts
packages/core/src/spec/lib/androidSdk/AndroidSdkToolsSpec.ts

- apksigner.bat depends on find_java.bat, which is broken in the
Android CLI tools.
- This implements a workaround that runs `apksigner.jar` directly.

Runs `apksigner.jar` instead of `apksigner.bat` on win32

---

packages/core/src/lib/TwaManifest.ts
packages/core/src/spec/lib/TwaManifestSpec.ts

As a quality measure, app shortcut icons must be at least half of the device's ideal size on Android, which is 48dp.
[Devtools](https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/2224796 ) and [documentation](https://web.dev/app-shortcuts/#icons-(optional)) have been updated. Let's now update bubblewrap as well ;)
@andreban @rayankans

Requires minimum size for app shortcut icons

---

packages/cli/src/lib/cmds/init.ts

Changed the notification in the bubblewrap/packages/cli/src/lib/cmds/init.ts for the build step.

Update the command notification for build

---

packages/cli/src/lib/cmds/init.ts
packages/core/src/lib/TwaGenerator.ts
packages/core/src/lib/TwaManifest.ts
packages/core/src/spec/lib/TwaManifestSpec.ts
packages/core/template_project/app/src/main/AndroidManifest.xml

Adds `monochromeIconUrl` following the same format as the generic & maskable icons. Android deals with transforming notification images so no additional work is needed to follow the spec! Additionally fixed up some indentation.

Closes #180: Use monochrome icon for notifications

---

packages/cli/src/lib/Cli.ts
packages/cli/src/lib/config.ts
packages/cli/src/spec/configSpec.ts

- Added missing `await` calls to fix Unhandled Promis Rejections
when renaming the old config name to the new config name.
- Defaults CLI to the `help` command
- Uses `.bubblewrap` as the name for the config folder, in case we need to store other files in the future.
@chenlevy24 FYI

Fixes Unhandled Promise Rejections

---

packages/core/src/lib/Result.ts
packages/core/src/spec/lib/ResultSpec.ts

The `Result` class should be used when invoking code where we
expect the result to be an error.

Adds the `Result` class

---

packages/cli/src/lib/Prompt.ts
packages/cli/src/lib/cmds/init.ts
packages/cli/src/lib/strings.ts

- Splits prompts into sections
- Adds more information to each section
See how it looks like below:

Improve prompts for the `init` command

---

packages/core/src/lib/GradleWrapper.ts
packages/core/src/lib/util.ts
packages/core/src/spec/lib/GradleWrapperSpec.ts

- Introduces a GradleWrapper method to call gradle bundleRelease
to produce app bundles as output.
This moves forward work for #119

GradleWrapper can call bundleRelease

---

packages/cli/README.md

This is the contents of the JDK I've just downloaded:

OpenJDK contains lib, but not com

---

packages/core/template_project/app/build.gradle
packages/core/template_project/build.gradle
packages/core/template_project/gradle/wrapper/gradle-wrapper.properties

- Bumps using android-browser-helper 1.3.2, for updated Chrome OS
support.
- Updates the Gradle Plugin and Gradle versions in order to
support the Android 11 `queries` section used on
`android-browser-helper`.

Support of Android 11 and CrOS support update

---

packages/cli/README.md

`Content` should probably be `Contents`:
```sh
➜  jdk1.8.0_261.jdk ls
Contents
```

fix: macOS JDK location - Content -> Contents

---

packages/core/src/lib/ShortcutInfo.ts
packages/core/src/lib/TwaGenerator.ts
packages/core/src/lib/TwaManifest.ts
packages/core/src/lib/util.ts
packages/core/src/spec/lib/ShortcutInfoSpec.ts
packages/core/src/spec/lib/utilSpec.ts

Pulls `ShortcutInfo` into its own module and delegates some logic there, simplifying TwaManifest.

Extract ShortcutInfo module

---

packages/cli/tsconfig.json
packages/core/src/spec/lib/GradleWrapperSpec.ts
packages/core/src/spec/lib/jdk/KeyToolSpec.ts
packages/core/tsconfig.json
packages/validator/tsconfig.json

This one small trick will save tons of code! [Node v10](https://node.green/) supports all es2018 syntax, and using it means async functions and classes aren't transpiled and are easier to debug.

Export es2018 code

---

packages/cli/README.md

- Adds docs on flags for the `install` command.
- Adds docs for the `generateAppBundle` for the `build` command.
- Adds docs for environmental variables for the `build` command.
Closes #222

Docs with more build flags and env variable info

---

packages/core/src/lib/TwaManifest.ts
packages/core/src/spec/lib/TwaManifestSpec.ts
packages/core/template_project/app/build.gradle
packages/core/template_project/app/src/main/AndroidManifest.xml

- Add a variable enableSiteSettingsShortcut into TwaManifest.ts that defaults to true
- Add ManageDataLauncherActivity into the template manifest
- Add enableSiteSettingsShortcut into tests
Behaviour tested by running npm run test and also by building an .apk and launching it in an android emulator.

Add site settings shortcut generation

---

package-lock.json
package.json
packages/cli/package.json
packages/core/package.json
packages/validator/package.json

- Removes @bubblewrap/code@1.4.0 dependency from root package,
which was pulling in sharp.
- Move all devDependencies to root package.json (@types/jasmine
and @types/mock-fs).
- Ensures develoment only dependencies are not included in runtime
dependencies.
- Fixes list of files included on the final package to exclude
testing code.

Sanitize package.json files

---

package-lock.json
package.json
packages/cli/package.json
packages/core/package-lock.json
packages/core/package.json
packages/validator/package-lock.json
packages/validator/package.json

- Running `npm run clean` cleans all `dist` folders.
- Renamed previous `clean` to `clean-modules`. That removes
`node_modules`.

Added `npm run clean`

---

packages/core/src/lib/TwaManifest.ts
packages/core/src/spec/lib/TwaManifestSpec.ts
packages/core/template_project/app/build.gradle
packages/core/template_project/app/src/main/AndroidManifest.xml

Add support for changing navbar divider color in TWAs generated via bubblewrap
Users required the ability to change the color of the navigation bar
divider custom tabs, which in some cases looked inconsistent. After adding
this feature to chromium and androidX, this PR adds it into bubblewrap
via a navigationColor variable that can be set in the web-manifest.json
Test: Tested the integration of bubblewrap and android-browser-helper 
by building an example app and changing the navbar color. 
Also modified tests to account for new navbar color variables.
Closes #66

Add divider color functionality

---

packages/core/src/lib/TwaManifest.ts
packages/core/src/spec/lib/TwaManifestSpec.ts
packages/core/template_project/app/src/main/AndroidManifest.xml

This changes the TWAManifest to specify whether the build should be
designated as a ChromeOS Only package for distribution through Play.
Otherwise, the build will be available to all devices.
Closes #320

Enable a ChromeOS Only Build

---

packages/core/src/lib/util.ts
packages/core/src/spec/lib/utilSpec.ts

This function is used to delete a file or directory hierarchy and
will be used to clean an existing project before regenerating it.
More context in #326

Added the `rmdir` method

---

packages/core/src/lib/TwaManifest.ts
packages/core/src/spec/lib/TwaManifestSpec.ts

`update` was crashing with method not found: `assetName`. Loading
the JSON from the file doesn't automatically assign methods to
the shortcut. So, we create proper shortcuts when creating the
TwaManifest from the JSON.

Fixed reading shortcuts from twa manifest

---

packages/cli/src/lib/config.ts
packages/core/src/index.ts
packages/core/src/lib/jdk/JdkInstaller.ts

If JDK 8 is not already installed, JdkInstaller will download
the binary and source code at given path.

Add JdkInstaller

---

packages/cli/src/spec/DoctorSpec.ts
packages/core/src/lib/jdk/JdkHelper.ts
packages/core/src/spec/lib/jdk/JdkHelperSpec.ts

- Fixed type.
- Added the JDK path to the error message.
- Fixed tests failing on MacOS due to platform differences.

Improved error messages and fixes tests running on MacOS

---

packages/cli/README.md
packages/cli/src/lib/cmds/init.ts

It was brought to my attention that most developers pursuing bubblewrap
would already know that they want to specify a ChromeOS only build. This
allows those developers to specify ChromeOS only from the beginning,
preventing them from needing to go back and modify the TWA-Manifest file
later on.

Add the Chrome OS only flag to init.

---

packages/core/src/lib/util.ts

- When set, the function is invoked for every chunk received.
- If we're unable to determine the total file size, the function
is invoked with totalSize as -1.

Added a progress function to util.downloadFile

---

packages/core/src/lib/features/AppsFlyerFeature.ts
packages/core/src/lib/features/FeatureManager.ts
packages/core/src/lib/features/FirstRunFlagFeature.ts
packages/core/src/spec/lib/features/AppsFlyerFeatureSpec.ts
packages/core/src/spec/lib/features/FeatureManagerSpec.ts
packages/core/src/spec/lib/features/FirstRunFlagFeatureSpec.ts

- Features were automatically enabled when added to the twa-manifest.
- This allows finer control and disabling features without removing
them from the Manifest.

Allows enabling/disable a feature in the twa-manifest.

---

packages/core/src/lib/TwaManifest.ts
packages/core/src/lib/features/FeatureManager.ts
packages/core/src/spec/lib/features/FeatureManagerSpec.ts
packages/core/template_project/app/build.gradle

Added alphaDependencies to `twaManifest.json` and added a check of that field in `app/build.gradle`. If it turned on, we will use version 2.0 of androidBrowserHelper, else we will use the current version.

Added alphaDependencies

---

packages/core/src/lib/TwaManifest.ts
packages/core/src/lib/types/WebManifest.ts

Added an optional share_target field to the webManifest

Web share target support

---

packages/core/template_project/app/build.gradle

Now we save the share target data as a string resource.

Web share target support - string resources save

---

packages/core/src/lib/TwaManifest.ts

The share_target implementation is breaking the build. This PR
fixes what is breaking it.
We also set the shareTarget variable to `undefined`, effectively
disabling the feature. The reason being that no validation is
being done in the value read from the Web Manifest, which can
potentially generate an invalid TWA Manifest.
Related to #21

Commented out share_target implementation

---

packages/cli/src/lib/AndroidSdkToolsInstaller.ts
packages/cli/src/lib/JdkInstaller.ts
packages/cli/src/lib/Prompt.ts
packages/cli/src/lib/config.ts
packages/cli/src/lib/strings.ts
packages/cli/src/spec/mock/MockPrompt.ts
packages/core/src/index.ts

- Moves JdkInstalled and AndroidSdkInstaller to `cli`, as apps
using `core` should build their own configs.
- Displays a progress bar when downloading the JDK Sources, the
JDK Binaries and the Android SDK.
- Displays messages when decompressing JDK Sources, JDK Binaries
and the Android SDK.
Closes #349

Added progress bar when downloading SDKs

---

packages/core/src/lib/TwaManifest.ts
packages/core/src/lib/features/FeatureManager.ts
packages/core/src/spec/lib/features/FeatureManagerSpec.ts

- Updates ABH version.
- `features` in TwaManifest defaults to an empty object.
- `LocationDelegationFeature` can only be enabled when
`alphaDependencies` are enabled.

Update abh-alpha to 2.1.0-alpha01

---

packages/core/src/lib/TwaManifest.ts
packages/core/template_project/app/src/main/AndroidManifest.xml

- Derive the full action URL from the Web Manifest URL.
- Extracts mime-types from share-target.
Improves #21

shareTarget derives full action URL

---

packages/cli/README.md
packages/cli/src/lib/Cli.ts
packages/cli/src/lib/cmds/help.ts
packages/cli/src/lib/cmds/init.ts
packages/cli/src/lib/inputHelpers.ts
packages/cli/src/lib/strings.ts
packages/core/src/index.ts
packages/core/src/lib/TwaManifest.ts
packages/core/src/spec/lib/TwaManifestSpec.ts
packages/core/template_project/app/build.gradle
packages/core/template_project/app/src/main/AndroidManifest.xml

- Handles orientation in twa-manifest.json, AndroidManifest.xml and init
- Adds an `alphaDependencies` parameter to `init`.
- Prompt for orientation only happens when that's enabled.

Handles orientation in twa-manifest.json, AndroidManifest.xml and init

---

packages/core/src/lib/jdk/KeyTool.ts
packages/core/src/spec/lib/jdk/KeyToolSpec.ts

See https://stackoverflow.com/questions/11808391/keytool-error-java-io-ioexceptionincorrect-ava-format
Closes #373

Escapes commas in dname when generating the signing key

---

packages/core/src/lib/TwaManifest.ts
packages/core/src/lib/features/FeatureManager.ts
packages/core/src/lib/features/PlayBillingFeature.ts
packages/core/src/spec/lib/features/FeatureManagerSpec.ts

Hey Andre, what do you think of this?
It's still a little rough at the moment - it doesn't actually build - I'm getting this error:
```
cli ERROR Command failed: ./gradlew assembleRelease --stacktrace                                                                                                                   
FAILURE: Build failed with an exception.                                                                                                                                           
* What went wrong:                                                                                                                                                                 
Could not determine the dependencies of task ':app:lintVitalRelease'. …
```

Add a Play Billing feature.

---

packages/core/src/lib/features/EmptyFeature.ts
packages/core/src/lib/features/Feature.ts
packages/core/src/lib/features/FeatureManager.ts
packages/core/src/lib/features/LocationDelegationFeature.ts
packages/core/src/lib/features/PlayBillingFeature.ts
packages/core/src/spec/lib/features/FeatureManagerSpec.ts
packages/core/template_project/app/src/main/java/DelegationService.java

This PR follows up from #410 and makes the variable name a bit more apt.

Rename classConstructor to onCreate.

---

packages/cli/src/lib/cmds/shared.ts
packages/core/src/index.ts
packages/core/src/lib/BufferedLog.ts
packages/core/src/lib/TwaGenerator.ts
packages/core/src/lib/features/FeatureManager.ts
packages/core/src/spec/lib/BufferedLogSpec.ts

This PR adds the `BufferedLog` class, a log that wraps another log and delays calls to any of the logging methods until `flush` is called.
This is used when we want to log something while showing a progress bar. If we logged while showing a progress bar we'll get mess output (Issue #416). Now we can buffer all the log messages until the progress bar has finished.
It also changes the warning presented when the user is trying to build with location delegation and play billing, but not with alpha dependencies into an error. In a follow up PR I'll add a check to ensure `enableNotifications` is `true`. I also believe that we should make the bubblewrap return code be non-zero as well.

Add BufferedLog and use it when generating the TWA.

---

packages/cli/src/lib/cmds/init.ts
packages/core/src/lib/features/FeatureManager.ts
packages/core/src/lib/features/PlayBillingFeature.ts
packages/core/src/spec/lib/features/FeatureManagerSpec.ts

- Uses androidbrowserhelper:2.1.0.
- Uses locationdelegation:1.0.0.
- Uses billing:1.0.0-alpha05.
- Updates CLI to always ask the orientation question.
- Updates LocationDelegation feature to not depend on alphaDependencies

Updates project dependencies

---

packages/cli/src/lib/cmds/init.ts
packages/cli/src/lib/strings.ts

- When running `init` with the `--directory` option,
`twa-manifest.json` was generated in the current directory
instead of the project directory.
- The `init` method would also suggest the current directory as
the default for the keystore. This is changed to be inside the
target directory.
Closes #414

Generate config and keys on the correct directory

---

packages/core/template_project/app/src/main/AndroidManifest.xml

Hello and thanks for this great work.
I spent a few time to figure out why my app was restarting at the `starturl` each time it was relaunched from the homescreen, even a few second after switching with an other app.
It seems that adding `android:alwaysRetainTaskState="true"` in `AndroidManifest.xml` is the standard solution to prevent that, and that it is a generally observed behaviours on other Android app (as well as for Chrome or other browsers too).
What do you think about adding this parameter by default ?

Retain task state by default

---

README.md

The ChromiumDev slack channel is being deprecated.

Remove mention to slack channel

---

packages/cli/README.md

- Bubblewrap now automatically installs its dependencies. Moves
the manual setup documentation to the bottom and highlights
developers should prefer the automated setup

Updates the "Environment Setup" section of the CLI docs

---

packages/core/template_project/app/build.gradle

`gradle assembleRelease` is reporting "Instantiable" errors like:
- Application must extend android.app.Application
- ManageDataLauncherActivity must extend android.app.Activity
- FileProvider must extend android.content.ContentProvider
- DelegationService must extend android.app.Service
Disabling the linter temporarily, as the code is correct and until
disabling / working around specific errors.
Full report:
```
> Task :app:lintVitalRelease FAILED
D:\Projects\twa-project\app\src\main\AndroidManifest.xml:30: Error: Application must extend android.app.Application [Instantiatable]
android:name="Application"
~~~~~~~~~~~
D:\Projects\twa-project\app\src\main\AndroidManifest.xml:55: Error: ManageDataLauncherActivity must extend android.app.Activity [Instantiatable]
<activity …
```

Disable gradle lint when building Android project

---

packages/core/src/lib/TwaGenerator.ts

- When the shareTarget element contains both text/url/title and
the files element, add "text/plain" and the mime-types from
the files.
Should fix #451

Fixes Web Share for both text/plain and files

---

packages/cli/src/lib/cmds/build.ts

- Developers reported the need to generate "unsigned" APKs and
Bundles, as signing packages is sometimes generated as part of
a CI or by different teams (see #413).
- This PR splits build and signing steps into two methods and paves
the way for a next PR that will enable passing a parameter to
skip the signing step.
- We also move constant file names to `consts`.

Separate build and sign steps for buildApk and buildAppBundles

---

packages/cli/README.md
packages/cli/src/lib/cmds/build.ts
packages/cli/src/lib/cmds/help.ts

**Problem:** The directory with our `twa-manifest.json` and the directory we're running the Bubblewrap commands from are different.
**Solution:** Add a `--manifest` option to the `bubblewrap build` command which allows the user to specify a directory where the client should look for `twa-manifest.json`, much like that option for the `bubblewrap update` command.

Add --manifest option for build script

---

packages/cli/README.md
packages/cli/src/lib/cmds/build.ts
packages/cli/src/lib/cmds/help.ts
packages/cli/src/lib/strings.ts

**Problem:** In our use case, we have to upload our unsigned APK/App Bundle to another service to be signed by people with the correct internal permissions for signing Android apps.
**Solution:** Add a `--skipSigning` option to the `bubblewrap build` command so that we can get an unsigned, built APK/App Bundle as output with a successful exit code.

Add --skipSigning option to build command

---

packages/cli/src/lib/cmds/help.ts

While investigating #486, I noticed that help text was missing the fingerprint command.

Update help.ts for fingerprint generateAssetLinks

---

packages/cli/README.md
packages/cli/src/lib/cmds/help.ts
packages/cli/src/lib/cmds/merge.ts

In our current flow for updating the TWA, we ran into the issue that we couldn't run `bubblewrap merge && bubblewrap update` in a way that would allow us to increment the version (only once) and change the version name. `bubblewrap update` allows us to do both things, but `bubblewrap merge` doesn't allow us to name the version or to skip upgrading. So, I'm suggesting replicating the logic for `update` in `merge`.

Allow skip version upgrade and setting version name on merge

---

packages/core/src/lib/ImageHelper.ts
packages/core/src/lib/TwaGenerator.ts

[UPDATED]
Upscaling images using Jimp can generate artifacts when transparent pixels are blended with opaque pixels.  See #488 for more details on the issue.
This happens because, even though the alpha channel sets the pixel to fully transparent, those pixels still have an RGB part to their color. 
As example, if a transparent pixel is `#000000FF` is a transparent pixel that has a black RGB part,  merging with an opaque white like`#FFFFFF00` will result in a semi-transparent grey (eg: `#7F7F7F7F`). However, what we want in this case is for the color to be a semi-transparent white (`#FFFFFF7F`).
Since we know the background color the splash icon is going to be rendered against we can assign the RGB part of the background color to all fully transparent pixels, so that the opaque pixels will …

Fixes artifacts when upscaling images for the Splash Screen

---

packages/core/src/lib/util.ts
packages/core/src/spec/lib/utilSpec.ts
packages/core/template_project/app/src/main/AndroidManifest.xml
packages/core/template_project/app/src/main/java/LauncherActivity.java

- Devices running Android 8.0 and below crash when a screen
orientation is set and the theme is transparent.
- We ensure only setting the screen orientation on Oreo and below.
- This doesn't affect how Chrome handles orientation, only the
splash screen.
Fixes #496

Doesn't set splash screen orientation on Oreo and below

---

packages/cli/src/lib/cmds/init.ts
packages/cli/src/lib/strings.ts

If a TWA needs geolocation, enable location delegation

Add prompt for location delegation to bubblewrap init

---

packages/cli/src/lib/cmds/update.ts
packages/cli/src/lib/strings.ts

- Move writing new version code and version name to twa-manifest.json
until after project is successfully generated. 
- Also edited and added messages to remind user to run `bubblewrap build`
after successful `bubblewrap update`.

Update twa-manifest.json after successful project generation

---

.github/workflows/nodejs.yml

- Version 14 is the current LTS version for Node.js.
- Version 16 is currently the latest, but the `canvas` dependency breaks the build, so skipping it for now.

Update Github Actions to run on NodeJs 14.x

---

packages/core/template_project/app/src/main/AndroidManifest.xml

Using android:value causes the resource to be interpreted as a
String and causes the Service to fail to retrieve the proper icon.

Uses android:resource for notification icon

---

packages/cli/src/lib/cmds/build.ts
packages/cli/src/lib/cmds/init.ts
packages/cli/src/lib/cmds/shared.ts
packages/cli/src/lib/cmds/update.ts
packages/cli/src/lib/strings.ts

Using checksum to track changes to `twa-manifest.json`, if a user tries to build a outdated version of the project, they will be prompted if they would like to apply the newest changes before building.

Auto apply twa manifest changes

---

packages/cli/src/lib/config.ts

This change checks for existing Android SDK and JDK installs so it does
not overwrite existing installations on disk. The check is done by
seeing if the existing bubblewrap config has a value set for JDK and
AndroidSDK fields. This change aims to resolve issue #547 where the user
exits the installation process halfway through and then resumes again
and is prompted to reinstall the JDK.
Closes #547

Checks for existing JDK and AndroidSDK installs.

---

packages/cli/src/lib/cmds/init.ts
packages/cli/src/lib/strings.ts

This adds a warning for the Google Play Family Policy to let developers
know about being in compliance and also provides a link for them to
visit to find out more information.
Fixes #545

Add a warning for the play family policy.

---

packages/cli/src/spec/configSpec.ts

This adds a jdkPath and androidSdkPath to the config.json file. This
should stop the tests from crashing on the CI/CD bots.

Fix the tests.

---

packages/cli/src/lib/Cli.ts

In discussions that we have had, we decided it was best to disable the
play command before we cut another release of bubblewrap. Once we are
more confident in our ability with the command, we will turn it on for
expiremental use.

Disable the play command.

---

packages/cli/src/lib/cmds/build.ts
packages/cli/src/lib/strings.ts

This is supposed to fix what happens when a checksum file doesn't currently exist yet to verify the state of twa-manifest.json. This will happen for users updating to the most recent version of Bubblewrap and run `bubblewrap build` without running `bubblewrap update` which will generate the checksum. When `bubblewrap build` doesn't find the checksum file, it will prompt the user whether they would like to generate their project again (which will create checksum) or build without regenerating the project.

Fix missing checksum

---

packages/cli/src/lib/cmds/play.ts
packages/core/src/lib/GooglePlay.ts

This adds the serviceAccountJsonFile to the constructor for the
GooglePlay object. Additionally, it removes some redundant checks for
the versionCode check.

Add serviceAccountJson to constructor

---

packages/cli/src/lib/cmds/play.ts
packages/core/src/lib/GooglePlay.ts

The gradle bootstrapPlay command was extraneous. It synced the play
representation down in a file format that could be looked over. This
provided no benefit to the end user.

Remove init command.

---

packages/cli/src/lib/cmds/play.ts
packages/core/src/lib/GooglePlay.ts

This adds the capability to publish a bundle using the API directly
rather than depending on a gradle task.

Add publishing a bundle via API instead of Gradle.

---

packages/core/src/lib/features/PlayBillingFeature.ts

Play Billing UI is not showing up since bumping the dependency. While it gets resolved in android-browser-helper, revert the version for now.

Revert billing dependency

---

packages/cli/src/lib/cmds/play.ts
packages/core/src/lib/GooglePlay.ts
packages/core/template_project/app/build.gradle

This removes the gradle and triple-t dependency for Google Play
Publishing. This implementation now directly communicates with the
Google Play API. This allows us to have more fine grained control on
communicating with Play and build in more features to bubblewrap as
needed.

Removed gradle and TripleT Dependency for play.

---

packages/cli/src/lib/config.ts

This fixes a bug where the AndroidSDK could be downloaded twice because the config was not being saved if an invalid manifest was supplied. Adding the await will wait for the saveConfig method to finish before continuing execution.

Await the saveConfig

---

packages/core/package-lock.json
packages/core/package.json
packages/core/src/lib/wrappers/svg2img.ts

An update to canvg (3.0.8) broke `svg2img`. We're pinning the canvg
version to 3.0.7 until the issue is fixed in the underlying libs.
Fixed #593

Pins canvg version to 3.0.7

---

packages/core/src/lib/jdk/KeyTool.ts
packages/core/src/lib/util.ts
packages/core/src/spec/lib/jdk/KeyToolSpec.ts
packages/core/src/spec/lib/utilSpec.ts

The ", $, `, and \ characters still needs to be escaped in double
quoted parameters for shell commands. Those are better handled
in this PR.
Fixes #587

Improves escaping for shell commands

---

packages/cli/src/lib/cmds/play.ts
packages/cli/src/lib/strings.ts
packages/core/src/lib/GooglePlay.ts
packages/core/src/lib/TwaManifest.ts
packages/core/src/spec/lib/TwaManifestSpec.ts

This adds the retain bundles feature to the Google Play integration.
This allows users when trying to publish an Android App bundle the
ability to select which bundles they would like to retain. This is
important for when a developer wants to release a ChromeOS only release
alongside an Android release.

Add retain bundles feature

---

packages/cli/src/lib/cmds/play.ts

This fixes a bug with removing retained bundles from the list of bundles
we want to retain. Previously removeRetained would be called and nothing
would occur to the list of bundles.

Fixes a retained bundles bug.

---

packages/cli/src/lib/cmds/play.ts

This supports changing the app version name on version checks if it
matches the version code listed in twa-manifest.json.

Support changing the versionName on versionCheck.

---

packages/core/src/lib/features/FeatureManager.ts
packages/core/src/spec/lib/features/FeatureManagerSpec.ts
packages/core/template_project/app/build.gradle
packages/core/template_project/app/src/main/AndroidManifest.xml

- Updates to android-browser-helper 2.3.0
- Adds android:exported to LauncherActivity
- Updates app/build.gradle to targetSdk 31

Support and use targetSdk 31

---

packages/core/src/lib/TwaManifest.ts
packages/core/src/lib/features/ArCoreFeature.ts
packages/core/src/lib/features/EmptyFeature.ts
packages/core/src/lib/features/Feature.ts
packages/core/src/lib/features/FeatureManager.ts
packages/core/template_project/app/src/main/AndroidManifest.xml

- Adds a feature that appends the AR Core requirement to the
AndroidManifest, ensuring the app is only deployed to devices that
support ARCore.
Closes #515

Adds the ArCore feature

---

packages/cli/src/lib/Cli.ts
packages/cli/src/lib/cmds/play.ts

This creates the playPublish command rather than the all in one play
command. This is a series of changes to complete migrating the commands
out to a less confusing state for our users.
See Google Play Integration #618
Fixes: Migrate play command to playPublish command #619

Create playPublish command.

---

packages/cli/src/lib/Cli.ts
packages/cli/src/lib/cmds/play.ts

This seperates versionchecking from a unified Play command into its
own versionCheck command.
Fixes #623

Migrate versionCheck to its own command.

---

packages/core/src/lib/ImageHelper.ts

Report icon url when svg2img throws an error.

---

packages/core/src/lib/FetchUtils.ts

This changes the user agent that is being sent to sites to match that of
a browser. Some sites were blocking our requests because of the default
user agent. node-fetch has some issues when attempting to set the user
agent, so this was left alone for now, especially because in #552 there
is a mention of potentially removing the user agent.

Set a default user-agent

---

packages/cli/src/lib/JdkInstaller.ts
packages/cli/src/lib/strings.ts

This updates the JDK used to match the JDK that is currently distributed
by Android Studio. This would help keep the building of Android apps
consistent between Android Studio and Bubblewrap. Additionally, this
unlocks the ability for bubblewrap to support keystores that utilize
aes encrypted keys.

Update JDK 8 to JDK 11

---

packages/core/src/lib/jdk/JdkHelper.ts
packages/core/src/spec/lib/jdk/JdkHelperSpec.ts

- Updates validatePath() to check for the version, according to the
`release` file.
- Fixes related test.

Fixes check for JDK version

---

packages/cli/src/lib/cmds/doctor.ts
packages/cli/src/spec/DoctorSpec.ts
packages/cli/src/spec/configSpec.ts

The tests in DoctorSpec seemed to be causing the test suite to abort,
and broken tests weren't being properly reported. My guess is that
many of the tests in DoctorSpec have actually never worked.
This PR fixes DoctorSpec and other tests that were broken.

Fix tests for Doctor

---

packages/cli/src/lib/cmds/build.ts

Removes the criteria validation from the build step for two reasons:
- The TWA criteria has changed, so the validation criteria doesn't
reflect the truth anymore.
- Additionally, the PSI/Lighthouse endpoint frequently fails to return
results.
We should also consider deprecating the validation command and package.

Remove criteria validation from the build step

---

packages/core/src/lib/util.ts
packages/core/src/spec/lib/utilSpec.ts

- Check for Java keywords when testing.
- Add _ before a keyword when generating.
See #672 for details

Handle Java keywords for applicatoinIds

---

packages/core/src/spec/lib/utilSpec.ts
packages/core/template_project/app/build.gradle

Escapes the gradle string before escaping the JSON. This ensures single quotes
are escaped.
Fixes #673

Escape gradle string in shareTarget / build.gradle

---

packages/cli/README.md
packages/cli/src/lib/cmds/help.ts
packages/cli/src/lib/cmds/init.ts
packages/cli/src/lib/strings.ts
packages/core/src/lib/TwaManifest.ts
packages/core/src/lib/types/WebManifest.ts
packages/core/src/spec/lib/TwaManifestSpec.ts
packages/core/template_project/app/build.gradle
packages/core/template_project/app/src/main/AndroidManifest.xml

This pull request adds a `--metaquest` flag for generating _universal_ APKs compatible with Meta Quest devices that open Trusted Web Activity (TWA) on regular Android devices and open Meta Quest Browser on Meta Quest devices. This will allow to abandon `ovr-platform-util` in favor of Bubblewrap (e.g. in PWABuilder).

Fix #615 Add Meta Quest support

---

packages/core/template_project/app/build.gradle

This PR intends to fix the following two things in the comments of the `build.gradle` file:
- The [demo app URL](https://svgomg.firebaseapp.com/) is hardcoded at `hostName` part of the config.
- Two minor typos.

Typo Fixes: Fix typos and hardcoding in comments of build.gradle config file

---

packages/core/src/lib/features/FeatureManager.ts
packages/core/template_project/app/src/main/AndroidManifest.xml

This makes notifications work again on Android 13 (and newer) by declaring an activity for showing the notification permission request prompt.
Potentially fixes #730

Show notification permission request prompt on Android T+

---

packages/cli/README.md

Update the text for manually setting up the Environment of README.md to avoid the following issue if OpenJDK 8 is used:
$ bubblewrap doctor
,-----.        ,--.  ,--.  ,--.
|  |) /_,--.,--|  |-.|  |-.|  |,---.,--.   ,--,--.--.,--,--.,---.
|  .-.  |  ||  | .-. | .-. |  | .-. |  |.'.|  |  .--' ,-.  | .-. |
|  '--' '  ''  | `-' | `-' |  \   --|   .'.   |  |  \ '-'  | '-' '
`------' `----' `---' `---'`--'`----'--'   '--`--'   `--`--|  |-'
`--'    
doctor ERROR Unsupported jdk version. Please download "OpenJDK 11(LTS)" at the link below: https://adoptopenjdk.net/releases.html?variant=openjdk11&jvmVariant=hotspot.

Update README.md with requirement for OpenJDK 11

---

.github/workflows/docker.yml
Dockerfile
packages/cli/README.md

Add a docker image which ships the bubblewrap cli (with all needed dependencies like java & android-sdk). This docker image can be used to easily run the cli as container for local use or for example in CI systems.
To build the container image this PR introduces a new Github workflow pushing the container image to <https://ghcr.io>. The workflow will create a `:next` tagged image on pushes to the `main` branch and to git tags / releases it will push an image with the tag name without the `v` prefix.

feat: add docker image for cli

---

packages/core/src/lib/TwaManifest.ts

**Describe the issue**
The shortcuts attribute is not working and the comments on how to do this is also wrong.
```diff
* shortcuts: [
*      // Insert shortcuts here, for example:
- *      // [name: 'Open SVG', short_name: 'Open', url: '/open', icon: 'splash']
+ *      // { name: 'Open SVG', shortName: 'Open', url: '/open', chosenIconUrl: 'https://example.com/example.svg' }
*  ],
```
1. The comment above should actually be an object rather than an array.
2. There should be `chosenIconUrl` according to the cli.
3. It should be `shortName` not `short_name` as it creates errors.
```
C:\Users\USER\AppData\Roaming\npm\node_modules\@bubblewrap\cli\node_modules\@bubblewrap\core\dist\lib\util.js:299
return input.replace(/[\\']/g, '\\\\\\$&');
^
TypeError: Cannot read properties of undefined …
```

Update TwaManifest.ts shortcut comment

---

packages/cli/src/lib/strings.ts

- Sets Bubblewrap handling installations as recommended.
- Clarifies JDK 11 when asking for paths.
See #793

Update JDK/Android SDK prompt strings

---

packages/cli/README.md

```
➜  docker run --rm -ti ghcr.io/GoogleChromeLabs/bubblewrap:latest build --config manifest.json 
docker: invalid reference format: repository name must be lowercase.
```
Not sure when this limitation came out.

docs: lowercase registry url for docker

---

packages/core/src/lib/features/PlayBillingFeature.ts

Bump android-browser-helper billing library to 1.0.0-alpha11, which is updated to Play Billing v6

Bump android-browser-helper billing library

---

packages/cli/package-lock.json
packages/cli/package.json
packages/core/package-lock.json

1. Fixes cli's dependency to core version 1.22.0
2. Updates versions to 1.22.0 in package-lock.json files

Bump cli dependencies in package.json and update package-lock.json files

---

packages/core/template_project/app/src/main/AndroidManifest.xml

Add pathPrefix to Android intent filter when "scope" is non-trivial.

Fix #883 Add pathPrefix=scope to Android intent filter

---

packages/core/src/lib/util.ts

Fix #853 
This PR fixes a node.js breaking security batch for windows devices https://github.com/nodejs/node/issues/52554 when runnint `bubblewrap build`
The original error was 
```
>> bubblewrap build
,-----.        ,--.  ,--.  ,--.
|  |) /_,--.,--|  |-.|  |-.|  |,---.,--.   ,--,--.--.,--,--.,---.
|  .-.  |  ||  | .-. | .-. |  | .-. |  |.'.|  |  .--' ,-.  | .-. |
|  '--' '  ''  | `-' | `-' |  \   --|   .'.   |  |  \ '-'  | '-' '
`------' `----' `---' `---'`--'`----'--'   '--`--'   `--`--|  |-'
`--'    
Please, enter passwords for the keystore A:\projects\55-sanaye\pwa\android\android.keystore and alias android.
? Password for the Key Store: ********
? Password for the Key: ********
? Password for the Key: ********
Building the Android App...
cli ERROR spawn EINVAL
```
I patched the …

Fix `spawn EINVAL` error on windows

---

packages/core/src/lib/util.ts

The original description mentioned the problem with `execFile()`, but the PR #881 updated both `exec()` and `execFile()`, where the `exec()` change was incorrect (see the [documentation](https://nodejs.org/api/child_process.html#child_processexeccommand-options-callback)), rolling it back.

Partial rollback of PR #881: exec() cannot have shell:true

---

Dockerfile
packages/cli/README.md

See:
- https://github.com/GoogleChromeLabs/bubblewrap/issues/860#issuecomment-2274000699
- https://github.com/GoogleChromeLabs/bubblewrap/issues/877
- https://github.com/GoogleChromeLabs/bubblewrap/issues/873

[1.22] Update Dockerfile to use JDK 17

---

packages/core/src/lib/TwaManifest.ts
packages/core/src/spec/lib/TwaManifestSpec.ts

Adds minimal-ui parsing support from web-manifest instead of returnign standalone.

Support minimal-ui display mode
