lib/TwaGenerator.js
package-lock.json
template_project/app/build.gradle
template_project/app/src/main/AndroidManifest.xml
template_project/app/src/main/res/xml/shortcuts.xml

Based on svgomg-twa: aedd667f9698f513ed3b0c2ccb4a5a99d9309b11

Updates to the template project

---

cli/cmds/build.js
cli/cmds/init.js
lib/androidSdk/AndroidSdkTools.js
lib/androidSdk/index.js
lib/jdk/JdkHelper.js
lib/jdk/index.js
package-lock.json
package.json
spec/lib/androidSdk/AndroidSdkToolsSpec.js
spec/lib/jdk/JdkHelperSpec.js
spec/support/jasmine.json

- Adds Jasmine as a Developer Dependency
- Adds tests for JdkHelper

Introduce tests

---

.github/workflows/nodejs.yml

Triggers validation for pull-requests

Updates Node CI Rules

---

cli/cmds/init.js
lib/TwaGenerator.js
template_project/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml

Creates an adaptive icon with an empty foreground and uses a maskable icon for the background.

Closes #2 - Generate adaptive icons

---

cli/cmds/init.js
lib/GradleWrapper.js
lib/TwaGenerator.js
lib/util.js
package-lock.json
package.json
spec/lib/utilSpec.js

Asks user for a suitable image when one is not available on the Web Manifest

---

cli/cmds/build.js
cli/cmds/init.js
cli/cmds/update.js
lib/TwaGenerator.js
lib/TwaManifest.js
lib/jdk/KeyTool.js
lib/jdk/index.js
package-lock.json
package.json
spec/lib/TwaManifestSpec.js
template_project/app/build.gradle

- Adds TwaManifest and test
- Adds an update CLI option, to rebuild a project based on an
existing Twa Manifest
- Skips generating the Signing Key on Init, if the file already
exists

Adds TwaManifest and enables update

---

package-lock.json
package.json
src/cli/index.js
src/lib/Config.ts
src/spec/lib/ConfigSpec.ts

- Also adds ConfigSpec.ts
- Adds Jasmine Types to Testing

Transforms Config into TypeScript

---

src/lib/TwaManifest.ts
src/spec/lib/TwaManifestSpec.ts
template_project/app/build.gradle
template_project/app/src/main/AndroidManifest.xml

- Updates both the template project and removes the old parameter
from llama-pack code.

Updates to use useBrowserOnChromeOS

---

src/lib/TwaManifest.ts
src/lib/types/WebManifest.ts
src/lib/util.js
src/spec/lib/utilSpec.js

Unify icon selection logic & fix some types.

Improve shortcut icon selection.

---

template_project/app/build.gradle
template_project/app/src/main/AndroidManifest.xml
template_project/build.gradle

- Replaces custom-tabs-client with the new library,
android-browser-helper

Uses android-browser-helper

---

src/cli/cmds/init.js

Fixes themeColor being used in pace of backgroundColor

---

src/cli/cmds/init.js
src/lib/TwaManifest.ts
src/spec/lib/TwaManifestSpec.ts
template_project/app/build.gradle
template_project/app/src/main/AndroidManifest.xml

Fix #61 
Implementation based on https://github.com/GoogleChromeLabs/llama-pack/issues/61#issuecomment-574596000

Add new launcherName field

---

src/lib/GradleWrapper.ts
src/lib/Log.ts
src/lib/TwaGenerator.ts
src/lib/androidSdk/AndroidSdkTools.ts
src/lib/jdk/JdkHelper.ts

- Not exhaustive, but should cover most places.

Adds missing private keywords

---

package-lock.json

- Updates dependencies to latest versions

Updates package-lock.json dependencies

---

packages/cli/README.md

This update to documentation includes the fix for #155 that is to make to simpler for a person to install and specify the requirements.

Updated Documentation for more detailed steps on requirements

---

packages/core/src/lib/jdk/KeyTool.ts
packages/core/src/lib/util.ts
packages/core/src/spec/lib/jdk/KeyToolSpec.ts

- Implements keytool -list and extracts fingerprints from the
response.

 Extract information from signing keys

---

README.md

I had some feedback that developers landing on the main README can feel a bit lost on where to get started. Linking to the Quick Start Guide and the CLI package to make it easier.
@agektmr FYI

Update main README.md to help devs get started

---

packages/cli/package.json
packages/cli/src/lib/Cli.ts
packages/cli/src/lib/cmds/version.ts

Adds version, --version and --help commands

---

packages/cli/src/lib/pwaValidationHelper.ts
packages/validator/src/lib/PwaValidator.ts
packages/validator/src/lib/psi/PsiResult.ts
packages/validator/src/spec/PwaValidatorSpec.ts

Adds Web Vitals metrics to validation

---

package-lock.json
package.json
packages/core/package-lock.json
packages/core/package.json
packages/core/src/lib/TwaGenerator.ts

now bubblewrap works with svg images

Changed the images library back to sharp

---

packages/cli/src/lib/config.ts

Change configuration file name from `llama-pack-config.json` to `bubblewrap-config.json`

Change configuration file name

---

packages/cli/src/lib/Prompt.ts
packages/cli/src/lib/cmds/build.ts
packages/cli/src/lib/cmds/init.ts
packages/cli/src/lib/cmds/update.ts
packages/cli/src/lib/inputHelpers.ts
packages/cli/src/lib/strings.ts
packages/cli/src/spec/inputHelpersSpec.ts
packages/core/src/index.ts
packages/core/src/lib/TwaManifest.ts

- Creates a Prompt class to wrap Inquirer.
- Moves prompt related strings to a different file, which should
make internationalization easier.
- Refactors inputHelpers to use Results.

Refactors user prompts

---

packages/cli/package-lock.json
packages/cli/package.json
packages/cli/src/lib/cmds/init.ts
packages/cli/src/lib/cmds/shared.ts
packages/cli/src/lib/cmds/update.ts
packages/cli/src/lib/strings.ts
packages/core/src/lib/TwaGenerator.ts

Uses a progress bar when generating Projects

---

packages/cli/README.md

Closes #235 
@d-koppenhagen FYI

Update CLI README.md with correct JDK path content on MacOS

---

packages/cli/src/lib/cmds/build.ts
packages/cli/src/lib/cmds/help.ts
packages/core/package-lock.json
packages/core/src/index.ts

- Refactors `build.ts` to have a `Build` class
- Moves APK generation to a method
- Adds method to generate App Bundles
- Adds a `build` flag to generate App Bundles
- Fixes stacktraces for the failed validation showing in the wrong place.
Closes #119

Adds App Bundle generation to the CLI

---

packages/cli/src/lib/cmds/help.ts

Fixed typo on help command

---

packages/core/template_project/app/build.gradle

- Template project has been updated in a previous PR

Bumped to use android-browser-helper 2.0.0

---

packages/core/src/lib/androidSdk/AndroidSdkTools.ts
packages/core/src/lib/jdk/JdkHelper.ts

Added a path validaton to jdkHelper and changed getJavaHome function to be static

JdkHelper - Added a path validation function

---

packages/cli/README.md

Include path instruction for spaces

---

README.md

Fixes #156 with a small note that refers to PWA Builder

Small addition of GUI tools to create APK

---

packages/cli/src/spec/configSpec.ts
packages/core/src/lib/jdk/JdkHelper.ts
packages/core/src/spec/lib/jdk/JdkHelperSpec.ts

Fixed a bug on 'JdkHelper's' 'validatePath' function and added tests to it.

Bug fix on JdkHelper + tests.

---

packages/cli/src/lib/config.ts
packages/cli/src/spec/configSpec.ts
packages/cli/src/spec/mock/MockPrompt.ts

Changed config.ts and it's tests to work with Prompt + Changed promptConfirm function to be more versatile.

Config.ts and its tests to work with Prompt + Minor addition to MockPrompt.ts

---

packages/cli/src/lib/cmds/doctor.ts
packages/cli/src/lib/cmds/updateConfig.ts
packages/cli/src/spec/DoctorSpec.ts
packages/cli/src/spec/configSpec.ts

Added tests for 'doctor' class and did minor changed in 'updateConfig', 'doctor' and 'configSpec'

Added tests for Doctor class

---

packages/cli/src/lib/strings.ts

Some small changes in `strings.ts`.

Fixed some typos in  strings.ts

---

packages/validator/README.md

Minimun becomes minimum.
Google CLA is signed!

Fix typo in README.md

---

packages/core/template_project/app/build.gradle

Fixed targetClass for shortcuts

---

packages/core/package-lock.json
packages/core/package.json
packages/core/src/lib/ImageHelper.ts
packages/core/src/lib/util.ts
packages/core/src/lib/wrappers/svg2img.ts
packages/core/src/spec/lib/utilSpec.ts

Changed `ImageHelper` and `util` to support svg type images.

Added svg support

---

packages/cli/src/lib/strings.ts

Error Message on updateConfigUsage misdirected users

chore: Update updateConfig usage message

---

packages/core/src/lib/TwaManifest.ts
packages/core/src/lib/features/AppsFlyerFeature.ts
packages/core/src/lib/features/Feature.ts
packages/core/src/lib/features/FeatureManager.ts
packages/core/src/lib/features/FirstRunFlagFeature.ts
packages/core/src/spec/lib/features/FeatureManagerSpec.ts
packages/core/src/spec/lib/features/FirstRunFlagFeatureSpec.ts
packages/core/template_project/app/src/main/java/LauncherActivity.java

-  When enabled, the `firstRunFlag` feature appends an extra
query parameter to the the launch URL. The first time the app
is launched, this parameter will contain the value `true`. On
the following launches, the parameter will have the value
`false`.
- This commit adds the feature, tests and modifies the template
project
- Closes #301

Added the firstRunFlag feature

---

packages/cli/src/lib/strings.ts

Fixes typo.

---

packages/core/src/spec/lib/TwaManifestSpec.ts

Added 2 tests to `twaManifestSpec.ts` to tests the new function `merge`.

Added tests to `merge` function on `core`.

---

packages/core/src/lib/features/FeatureManager.ts
packages/core/src/spec/lib/features/FeatureManagerSpec.ts
packages/core/template_project/app/src/main/java/DelegationService.java

- Also fixes issue with the DelegationService template

Bumps Bubblewrap to use abh-2.0.1

---

packages/cli/src/lib/config.ts

Create directory recursively installing JDK

---

packages/core/src/lib/TwaManifest.ts
packages/core/template_project/app/build.gradle

Fixed the web share target's string resource save on `build.gradle`

Web share target support - fixed bug

---

packages/core/src/lib/types/WebManifest.ts

- Type as defined at https://www.w3.org/TR/appmanifest/#orientation-member
Starts work on #281

Adds the OrientationLock to WebManifest

---

packages/core/src/lib/androidSdk/AndroidSdkTools.ts

Older versions of the the Android SDK add the initial files inside
the `tools` folder, which version `6858069` and above add it
directly to the `bin` folder.
Closes #397

Handles new directory structure for Android SDK

---

packages/core/src/lib/TwaGenerator.ts
packages/core/src/lib/util.ts
packages/core/template_project/app/build.gradle
packages/core/template_project/app/src/main/AndroidManifest.xml

Adds screen orientation to LauncherActivity so orientation is locked on the splash screen.

Adds screen orientation to LauncherActivity

---

packages/core/template_project/app/build.gradle
packages/core/template_project/app/src/main/AndroidManifest.xml

Sets LaunchActivity orientation value in the XML instead of using a resource.

Sets LaunchActivity orientation value in the XML

---

packages/core/template_project/app/src/main/java/DelegationService.java

I probably will want to change the name of the classConstructor field, but with this in place, your orientation fix and with notifications enabled, TWA Play Billing integration finally works.

Move the DelegationService constructor fields into onCreate.

---

packages/core/src/lib/androidSdk/AndroidSdkTools.ts

Otherwise it will fail on initial use on Windows 10.

Added .bat to sdkmanager before checking to see if the file exists.

---

packages/core/src/lib/jdk/KeyTool.ts
packages/core/src/spec/lib/jdk/KeyToolSpec.ts

Forces locale to en for keytool list

---

packages/core/src/lib/TwaManifest.ts
packages/core/src/lib/features/FeatureManager.ts
packages/core/src/spec/lib/features/FeatureManagerSpec.ts
packages/core/template_project/app/src/main/AndroidManifest.xml

Adds support for sticky-immersive to Bubblewrap

---

packages/core/src/lib/TwaGenerator.ts
packages/core/src/lib/TwaManifest.ts
packages/core/template_project/app/src/main/AndroidManifest.xml

Fixes support for simple Web Share Target

---

packages/core/template_project/app/build.gradle

Updates project template to target sdk 30

---

packages/core/src/lib/androidSdk/AndroidSdkTools.ts
packages/core/src/spec/lib/androidSdk/AndroidSdkToolsSpec.ts

- Tested on MacOS, Windows and Linux (via WSL)
Closes #467

Update Android build tools to 30.0.3

---

packages/cli/src/lib/cmds/build.ts
packages/cli/src/lib/cmds/help.ts
packages/core/src/lib/TwaManifest.ts
packages/core/src/lib/androidSdk/AndroidSdkTools.ts
packages/core/src/spec/lib/TwaManifestSpec.ts
packages/core/template_project/app/build.gradle
packages/core/template_project/build.gradle
packages/core/template_project/gradle/wrapper/gradle-wrapper.properties

This installs the GPP plugin into the template project. This will apply
the configuration files serviceAccountJsonFile key to the specified
files which will activate the GPP plugin.

Install the GPP plugin into the template project.

---

packages/cli/README.md
packages/cli/src/lib/cmds/build.ts
packages/cli/src/lib/cmds/help.ts

Add --signingKeyPath and --signingKeyAlias options to build command

---

packages/core/src/lib/GooglePlay.ts
packages/core/src/lib/GradleWrapper.ts
packages/core/template_project/app/build.gradle

This is the foundation of the Google Play Publisher integration I want. Making some large changes with regards to adding a GooglePlay.ts file and changing the GradleWrapper to accept user defined args.

Create a Play library to communicate with GPP.

---

packages/cli/src/lib/cmds/build.ts
packages/cli/src/lib/cmds/update.ts
packages/cli/src/lib/strings.ts

- Check that enableNotifications is true
- Check that alphaDependencies are enabled

Additional checks for when Play Billing is enabled

---

.github/workflows/nodejs.yml
README.md
packages/cli/README.md
packages/cli/src/lib/Cli.ts
packages/core/README.md

Drops support for Node 10

---

package-lock.json
package.json
packages/core/src/lib/TwaGenerator.ts
packages/core/src/lib/TwaManifest.ts
packages/core/src/spec/lib/TwaManifestSpec.ts
packages/core/template_project/app/build.gradle
packages/core/template_project/app/src/main/AndroidManifest.xml
packages/core/template_project/app/src/main/res/values/strings.xml

- Adds the `additionalOrigins` field to the `TwaManifest`.
- Adds `res/values/strings.xml`.
- Moves the `assetStatements` declaration to the resource file.
- Introduces additional origins resource and adds the meta-tags
and intent-filters in `AndroidManifest.xml`.
CC @jdecked

Adds support for additional origins

---

packages/core/src/lib/features/FeatureManager.ts
packages/core/src/lib/features/LocationDelegationFeature.ts
packages/core/src/spec/lib/features/FeatureManagerSpec.ts

- androidbrowserhelper:androidbrowserhelper:2.2.1
- androidbrowserhelper:locationdelegation:1.0.1

Update versions of android dependencies

---

.eslintrc.json
packages/cli/src/lib/cmds/shared.ts
packages/cli/src/lib/strings.ts

This adds a check to the updateProject command so it can validate the
iconUrl,

Validate iconUrl on update.

---

packages/cli/src/lib/cmds/play.ts
packages/cli/src/lib/strings.ts
packages/core/package-lock.json
packages/core/package.json
packages/core/src/lib/GooglePlay.ts
packages/core/src/lib/util.ts

This implements the getLargestVersion check from the Google Play
Publisher API. This should help our community query the largest version
of an uploaded bundle to the Play Store and ensure that they can update
their package to have a larger version than that uploaded.

getLargestVersion implementation.

---

packages/cli/README.md

These are documentation updates to explain the google play feature and how to use it.

Update README for Google play feature

---

packages/cli/src/lib/Cli.ts
packages/cli/src/lib/cmds/play.ts

This migrates the retaining capability into its own command.
Fixes Create playRetain command #622

Migrate play --retain to playRetain command.

---

README.md
packages/cli/README.md
packages/cli/src/lib/Cli.ts
packages/cli/src/lib/cmds/play.ts
packages/cli/src/lib/strings.ts
packages/core/src/lib/GooglePlay.ts
packages/core/src/lib/TwaManifest.ts
packages/core/src/spec/lib/TwaManifestSpec.ts
packages/core/template_project/app/build.gradle

This merges our changes of the Play Experiement over. Everything in this branch should have been previously reviewed.

Merge Play Experiment

---

packages/cli/package.json

Pin colors library to version 1.4.0

---

lerna.json
packages/cli/package-lock.json
packages/cli/package.json
packages/core/package-lock.json
packages/core/package.json
packages/core/src/lib/features/PlayBillingFeature.ts
packages/validator/package-lock.json
packages/validator/package.json

Update billing library reference.

---

packages/core/src/lib/ShortcutInfo.ts

Escape shortcut string in build.gradle

---

packages/core/package-lock.json
packages/core/package.json
packages/core/src/lib/ImageHelper.ts

Updates jimp from 0.14.x to 0.22.x

Updates jimp from 0.14.x to 0.22.x

---

packages/core/src/lib/features/PlayBillingFeature.ts

Update ABH billing dependency to point out to the new version 1.0.0-alpha10

Update ABH billing version to 1.0.0-alpha10

---

packages/cli/README.md
packages/core/src/lib/TwaManifest.ts
packages/core/src/spec/lib/TwaManifestSpec.ts
packages/core/template_project/app/build.gradle
packages/core/template_project/app/src/main/AndroidManifest.xml

Added customtabs.trusted.STATUS_BAR_COLOR_DARK.
Fixes #802

Add themeColorDark aka colorPrimaryDark aka STATUS_BAR_COLOR_DARK

---

packages/core/src/lib/features/LocationDelegationFeature.ts

Update locationdelegation dep to 1.1.1
